/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mcq;

/**
 *
 * @author NANCY
 */
import java.text.SimpleDateFormat;
import java.sql.*;
import Project.SQL_CONNECTION;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Date;
import java.awt.Color; 
public class StudentInfo extends javax.swing.JFrame {

    /**
     * Creates new form StudentInfo
     */
    public StudentInfo() {
        initComponents();
        jTextArea1.setEditable(false);
        SimpleDateFormat dFormat=new SimpleDateFormat("dd-mm-yyyy");
        Date date=new Date();
        lblDate.setText(dFormat.format(date));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRoll_No = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtFather_Name = new javax.swing.JTextField();
        txtMother_Name = new javax.swing.JTextField();
        combGender = new javax.swing.JComboBox<>();
        txtContact_No = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtHigh_1 = new javax.swing.JTextField();
        txtAve_1 = new javax.swing.JTextField();
        txtCompletion_1 = new javax.swing.JTextField();
        txtAve_2 = new javax.swing.JTextField();
        txtHigh_2 = new javax.swing.JTextField();
        txtCompletion_2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAve_3 = new javax.swing.JTextField();
        txtHigh_3 = new javax.swing.JTextField();
        txtCompletion_3 = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSave_Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setText("REGISTRATION FORM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Date:");

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDate.setText("jLabel3");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 102, 102));
        btnClose.setText("x");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Roll Number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Name :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Father Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Mother Name:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Gender :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Email:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("10th");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("12th");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Contact No:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("University");

        txtRoll_No.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        txtName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtFather_Name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtFather_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFather_NameActionPerformed(evt);
            }
        });

        txtMother_Name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        combGender.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        combGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", "I" }));

        txtContact_No.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        txtHigh_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtHigh_1.setText("Enter High School Name");
        txtHigh_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHigh_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHigh_1FocusLost(evt);
            }
        });

        txtAve_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAve_1.setText("Enter Your  Average");
        txtAve_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAve_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAve_1FocusLost(evt);
            }
        });

        txtCompletion_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCompletion_1.setText("Enter Year Of Completion");
        txtCompletion_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCompletion_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCompletion_1FocusLost(evt);
            }
        });

        txtAve_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAve_2.setText("Enter Your  Average");
        txtAve_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAve_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAve_2FocusLost(evt);
            }
        });

        txtHigh_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtHigh_2.setText("Enter High School Name");
        txtHigh_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHigh_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHigh_2FocusLost(evt);
            }
        });

        txtCompletion_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCompletion_2.setText("Enter Year Of Completion");
        txtCompletion_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCompletion_2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCompletion_2FocusLost(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Address :");

        txtAve_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAve_3.setText("Enter Your  Average");
        txtAve_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAve_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAve_3FocusLost(evt);
            }
        });

        txtHigh_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtHigh_3.setText("Enter University Name");
        txtHigh_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHigh_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHigh_3FocusLost(evt);
            }
        });

        txtCompletion_3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtCompletion_3.setText("Enter Year Of Completion");
        txtCompletion_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCompletion_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCompletion_3FocusLost(evt);
            }
        });

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAddress.setText(" ");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome to the  Yn-Growth online exam system ,\nthis system manages all the activities\nrelated to examination management  from\nreciept of Enrollment forms and examination\nforms through processing of Results and\ngrading Reports.\n");
        jScrollPane1.setViewportView(jTextArea1);

        btnSave_Next.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnSave_Next.setText("SAVE & NEXT");
        btnSave_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave_NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(68, 68, 68)
                                .addComponent(txtRoll_No, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHigh_3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHigh_2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMother_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHigh_1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(combGender, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFather_Name)
                                        .addComponent(txtName)
                                        .addComponent(txtContact_No, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAve_1)
                                    .addComponent(txtAve_2)
                                    .addComponent(txtAve_3))
                                .addGap(181, 181, 181)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCompletion_2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompletion_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompletion_3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(123, 123, 123)
                .addComponent(txtAddress)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(571, 571, 571)
                .addComponent(btnSave_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(lblDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(95, 95, 95)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack)
                            .addComponent(lblDate)
                            .addComponent(jLabel2))))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(txtMother_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtContact_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtRoll_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtFather_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtAve_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCompletion_1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtHigh_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtAve_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHigh_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCompletion_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtAve_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCompletion_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtHigh_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnSave_Next)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSave_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave_NextActionPerformed
        // TODO add your handling code here:
        String roll_number=txtRoll_No.getText();
        
        String name=txtName.getText();
        
        String father_name=txtFather_Name.getText();
        
        String mother_name=txtMother_Name.getText();
        
        String gender=(String)combGender.getSelectedItem();
        
        String contact_no=txtContact_No.getText();
        
        String email=txtEmail.getText();
        
        String grade_ten_high_school_name=txtHigh_1.getText();
        
        String grade_ten_average=txtAve_1.getText();
        
        String grade_ten_year_of_completion=txtCompletion_1.getText();
        
        String grade_twelve_high_school_name=txtHigh_2.getText();
        
        String grade_twelve_average=txtAve_2.getText();
        
        String grade_twelve_year_of_completion=txtCompletion_2.getText();
        
        String university_name=txtHigh_3.getText();
        
        String university_average=txtAve_3.getText();
        
        String university_year_of_completion=txtCompletion_3.getText();
        
        String address=txtAddress.getText();
        
        String marks="0";
        
        try{
            Connection con= SQL_CONNECTION.getcon();
            PreparedStatement ps=con.prepareStatement("insert into Student values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ");
            ps.setString(1,roll_number );
            
            ps.setString(2,name );
            
            ps.setString(3,father_name );
            
            ps.setString(4,mother_name);
            
            ps.setString(5,gender );
            
            ps.setString(6,contact_no );
            
            ps.setString(7, email);
            
            ps.setString(8,grade_ten_high_school_name  );
            
            ps.setString(9,grade_ten_average );
            
            ps.setString(10, grade_ten_year_of_completion );
            
            ps.setString(11,  grade_twelve_high_school_name);
            
            ps.setString(12,  grade_twelve_average);
            
            ps.setString(13,   grade_twelve_year_of_completion);
            
            ps.setString(14,university_name );
            
            ps.setString(15, university_average );
            
            ps.setString(16,university_year_of_completion );
            
            ps.setString(17, address );
            
            ps.setString(18, marks);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"You have successfully added "+ " " +name+""+" to the yn-growth database system!! ");
            setVisible(false);
            new TestInstructions(roll_number).setVisible(true);
            
            
        
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
                  
             
        
    }//GEN-LAST:event_btnSave_NextActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtFather_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFather_NameActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_txtFather_NameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home_Page().setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
            int a=JOptionPane.showConfirmDialog(null,"Are you sure that you want to exit the application ","Select", JOptionPane.YES_NO_OPTION );
        if(a==0){
            System.exit(1);
            
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtHigh_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHigh_1FocusGained
        // TODO add your handling code here:
        if(txtHigh_1.getText().equals("Enter High School Name")){
            txtHigh_1.setText("");
            txtHigh_1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtHigh_1FocusGained

    private void txtHigh_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHigh_2FocusGained
        // TODO add your handling code here:
           if(txtHigh_2.getText().equals("Enter High School Name")){
            txtHigh_2.setText("");
            txtHigh_2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtHigh_2FocusGained

    private void txtHigh_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHigh_3FocusGained
        // TODO add your handling code here:
           if(txtHigh_3.getText().equals("Enter University Name")){
            txtHigh_3.setText("");
            txtHigh_3.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtHigh_3FocusGained

    private void txtAve_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAve_1FocusGained
        // TODO add your handling code here:
          if(txtAve_1.getText().equals("Enter Your  Average")){
            txtAve_1.setText("");
            txtAve_1.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtAve_1FocusGained

    private void txtAve_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAve_2FocusGained
        // TODO add your handling code here:
               if(txtAve_2.getText().equals("Enter Your  Average")){
            txtAve_2.setText("");
            txtAve_2.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtAve_2FocusGained

    private void txtAve_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAve_3FocusGained
        // TODO add your handling code here:
               if(txtAve_3.getText().equals("Enter Your  Average")){
            txtAve_3.setText("");
            txtAve_3.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtAve_3FocusGained

    private void txtCompletion_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompletion_1FocusGained
        // TODO add your handling code here:
         if(txtCompletion_1.getText().equals("Enter Year Of Completion")){
            txtCompletion_1.setText("");
            txtCompletion_1.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_txtCompletion_1FocusGained
    }
    private void txtCompletion_2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompletion_2FocusGained
        // TODO add your handling code here:
        if(txtCompletion_2.getText().equals("Enter Year Of Completion")){
            txtCompletion_2.setText("");
            txtCompletion_2.setForeground(new Color(0,0,0));
    }                                       
    }//GEN-LAST:event_txtCompletion_2FocusGained

    private void txtCompletion_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompletion_3FocusGained
        // TODO add your handling code here:
        if(txtCompletion_3.getText().equals("Enter Year Of Completion")){
            txtCompletion_3.setText("");
            txtCompletion_3.setForeground(new Color(0,0,0));
    }                                       
    }//GEN-LAST:event_txtCompletion_3FocusGained

    private void txtHigh_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHigh_1FocusLost
        // TODO add your handling code here:
          if(txtHigh_1.getText().equals("")){
            txtHigh_1.setText("Enter High School Name");
            txtHigh_1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtHigh_1FocusLost

    private void txtHigh_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHigh_2FocusLost
        // TODO add your handling code here:
                if(txtHigh_2.getText().equals("")){
            txtHigh_2.setText("Enter High School Name");
            txtHigh_2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtHigh_2FocusLost

    private void txtHigh_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHigh_3FocusLost
        // TODO add your handling code here:
                      if(txtHigh_3.getText().equals("")){
             txtHigh_3.setText("Enter University Name");
            txtHigh_3.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtHigh_3FocusLost

    private void txtAve_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAve_1FocusLost
        // TODO add your handling code here:
          if(txtAve_1.getText().equals("")){
             txtAve_1.setText("Enter Your  Average");
            txtAve_1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtAve_1FocusLost

    private void txtAve_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAve_2FocusLost
        // TODO add your handling code here:
         if(txtAve_2.getText().equals("")){
             txtAve_2.setText("Enter Your  Average");
            txtAve_2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtAve_2FocusLost

    private void txtAve_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAve_3FocusLost
        // TODO add your handling code here:
         if(txtAve_3.getText().equals("")){
             txtAve_3.setText("Enter Your  Average");
            txtAve_3.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtAve_3FocusLost

    private void txtCompletion_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompletion_1FocusLost
        // TODO add your handling code here:
         if(txtCompletion_1.getText().equals("")){
             txtCompletion_1.setText("Enter Year Of Completion");
            txtCompletion_1.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtCompletion_1FocusLost

    private void txtCompletion_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompletion_2FocusLost
        // TODO add your handling code here:
          if(txtCompletion_2.getText().equals("")){
             txtCompletion_2.setText("Enter Year Of Completion");
            txtCompletion_2.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtCompletion_2FocusLost

    private void txtCompletion_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCompletion_3FocusLost
        // TODO add your handling code here:
          if(txtCompletion_3.getText().equals("")){
             txtCompletion_3.setText("Enter Year Of Completion");
            txtCompletion_3.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtCompletion_3FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave_Next;
    private javax.swing.JComboBox<String> combGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAve_1;
    private javax.swing.JTextField txtAve_2;
    private javax.swing.JTextField txtAve_3;
    private javax.swing.JTextField txtCompletion_1;
    private javax.swing.JTextField txtCompletion_2;
    private javax.swing.JTextField txtCompletion_3;
    private javax.swing.JTextField txtContact_No;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFather_Name;
    private javax.swing.JTextField txtHigh_1;
    private javax.swing.JTextField txtHigh_2;
    private javax.swing.JTextField txtHigh_3;
    private javax.swing.JTextField txtMother_Name;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRoll_No;
    // End of variables declaration//GEN-END:variables
}
